import json

with open("simple_local_rag.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

# Cell 1: Setup code
nb['cells'][1]['source'] = [
    "# Step 1: Create folders, install dependencies, and download local models\n",
    "from pathlib import Path\n",
    "import importlib\n",
    "import subprocess\n",
    "import sys\n",
    "\n",
    "PROJECT_ROOT = Path.cwd()\n",
    "MODEL_DIR = PROJECT_ROOT / \"MODEL\"\n",
    "EMBED_MODEL_DIR = MODEL_DIR / \"embeddings\" / \"all-MiniLM-L6-v2\"\n",
    "LLM_MODEL_DIR = MODEL_DIR / \"qwen2.5-3b-instruct-q4_k_m.gguf\"\n",
    "DATA_DIR = PROJECT_ROOT / \"data\"\n",
    "VECTOR_DIR = PROJECT_ROOT / \"vectorstore\"\n",
    "\n",
    "for folder in [MODEL_DIR, EMBED_MODEL_DIR.parent, DATA_DIR, VECTOR_DIR]:\n",
    "    folder.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "print(\"Project root:\", PROJECT_ROOT)\n",
    "print(\"Model directory:\", MODEL_DIR)\n",
    "\n",
    "# Install only missing packages so the notebook stays idempotent.\n",
    "required = {\n",
    "    \"sentence_transformers\": \"sentence-transformers\",\n",
    "    \"faiss\": \"faiss-cpu\",\n",
    "    \"torch\": \"torch\",\n",
    "    \"pypdf\": \"pypdf\",\n",
    "    \"llama_cpp\": \"llama-cpp-python\",\n",
    "}\n",
    "\n",
    "missing = []\n",
    "for module_name, package_name in required.items():\n",
    "    try:\n",
    "        importlib.import_module(module_name)\n",
    "    except Exception:\n",
    "        missing.append(package_name)\n",
    "\n",
    "if missing:\n",
    "    print(\"Installing missing packages:\", missing)\n",
    "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", *missing])\n",
    "else:\n",
    "    print(\"All required packages are already installed.\")\n",
    "\n",
    "from sentence_transformers import SentenceTransformer\n",
    "\n",
    "# Download embedding model to MODEL/embeddings/... if not already present.\n",
    "if (EMBED_MODEL_DIR / \"config_sentence_transformers.json\").exists():\n",
    "    print(\"Embedding model already present:\", EMBED_MODEL_DIR)\n",
    "    _embed = SentenceTransformer(str(EMBED_MODEL_DIR), local_files_only=True)\n",
    "else:\n",
    "    print(\"Downloading embedding model: sentence-transformers/all-MiniLM-L6-v2\")\n",
    "    _embed = SentenceTransformer(\"sentence-transformers/all-MiniLM-L6-v2\")\n",
    "    _embed.save(str(EMBED_MODEL_DIR))\n",
    "    print(\"Saved embedding model to:\", EMBED_MODEL_DIR)\n",
    "\n",
    "# Qwen GGUF model is expected to be in MODEL/qwen2.5-3b-instruct-q4_k_m.gguf\n",
    "if LLM_MODEL_DIR.exists():\n",
    "    print(\"LLM already present:\", LLM_MODEL_DIR)\n",
    "else:\n",
    "    print(f\"Please ensure {LLM_MODEL_DIR.name} is placed in the MODEL directory.\")\n",
    "\n",
    "print(\"Setup complete.\")\n",
    "print(\"Tip: Add one or more PDF files to the data folder before running Step 2.\")"
]

# Cell 5: RAG Inference
nb['cells'][5]['source'] = [
    "# Step 3 code: Local RAG inference (retrieve + generate)\n",
    "from pathlib import Path\n",
    "import json\n",
    "import faiss\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from llama_cpp import Llama\n",
    "\n",
    "PROJECT_ROOT = Path.cwd()\n",
    "EMBED_MODEL_DIR = PROJECT_ROOT / \"MODEL\" / \"embeddings\" / \"all-MiniLM-L6-v2\"\n",
    "LLM_MODEL_DIR = PROJECT_ROOT / \"MODEL\" / \"qwen2.5-3b-instruct-q4_k_m.gguf\"\n",
    "INDEX_PATH = PROJECT_ROOT / \"vectorstore\" / \"faiss_index.bin\"\n",
    "CHUNKS_PATH = PROJECT_ROOT / \"vectorstore\" / \"chunks.json\"\n",
    "\n",
    "if not INDEX_PATH.exists() or not CHUNKS_PATH.exists():\n",
    "    raise FileNotFoundError(\"Index files missing. Run Step 2 cell first.\")\n",
    "\n",
    "index = faiss.read_index(str(INDEX_PATH))\n",
    "chunks = json.loads(CHUNKS_PATH.read_text(encoding=\"utf-8\"))\n",
    "\n",
    "embedder = SentenceTransformer(str(EMBED_MODEL_DIR), local_files_only=True)\n",
    "print(\"Loading Qwen GGUF model...\")\n",
    "model = Llama(model_path=str(LLM_MODEL_DIR), n_ctx=2048, verbose=False)\n",
    "\n",
    "def retrieve_context(query: str, top_k: int = 3):\n",
    "    q_vec = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True).astype(\"float32\")\n",
    "    scores, ids = index.search(q_vec, top_k)\n",
    "    passages = []\n",
    "    for rank, (doc_id, score) in enumerate(zip(ids[0], scores[0]), start=1):\n",
    "        passages.append({\n",
    "            \"rank\": rank,\n",
    "            \"score\": float(score),\n",
    "            \"text\": chunks[int(doc_id)]\n",
    "        })\n",
    "    return passages\n",
    "\n",
    "def answer_question(question: str, top_k: int = 3, max_new_tokens: int = 160):\n",
    "    retrieved = retrieve_context(question, top_k=top_k)\n",
    "    context_block = \"\\n\\n\".join([f\"[{r['rank']}] {r['text']}\" for r in retrieved])\n",
    "\n",
    "    prompt = f\"\"\"<|im_start|>system\n",
    "You are a helpful assistant. Answer strictly using the context below. If the context does not contain the answer, say: \"I don't know based on the provided context.\"\n",
    "<|im_end|>\n",
    "<|im_start|>user\n",
    "Context:\n",
    "{context_block}\n",
    "\n",
    "Question: {question}<|im_end|>\n",
    "<|im_start|>assistant\n",
    "\"\"\"\n",
    "\n",
    "    output = model(\n",
    "        prompt,\n",
    "        max_tokens=max_new_tokens,\n",
    "        temperature=0.0,\n",
    "        stop=[\"<|im_end|>\"]\n",
    "    )\n",
    "\n",
    "    answer = output[\"choices\"][0][\"text\"].strip()\n",
    "    return answer, retrieved\n",
    "\n",
    "# Try your own question here\n",
    "question = \"what is vigyan bherav tantra? explain to a 5 year old\"\n",
    "answer, evidence = answer_question(question, top_k=3)\n",
    "\n",
    "print(\"Question:\", question)\n",
    "print(\"\\nAnswer:\\n\", answer)\n",
    "print(\"\\nRetrieved context:\")\n",
    "for item in evidence:\n",
    "    print(f\"\\n[{item['rank']}] score={item['score']:.4f}\\n{item['text']}\")"
]

# Cell 7: Normal vs RAG Comparison
nb['cells'][7]['source'] = [
    "# Step 4 code: Side-by-side comparison\n",
    "def normal_llm_answer(question: str, max_new_tokens: int = 160):\n",
    "    prompt = f\"\"\"<|im_start|>system\n",
    "You are a helpful assistant. Answer the question clearly and concisely.<|im_end|>\n",
    "<|im_start|>user\n",
    "{question}<|im_end|>\n",
    "<|im_start|>assistant\n",
    "\"\"\"\n",
    "\n",
    "    output = model(\n",
    "        prompt,\n",
    "        max_tokens=max_new_tokens,\n",
    "        temperature=0.0,\n",
    "        stop=[\"<|im_end|>\"]\n",
    "    )\n",
    "\n",
    "    return output[\"choices\"][0][\"text\"].strip()\n",
    "\n",
    "def compare_normal_vs_rag(question: str, top_k: int = 3):\n",
    "    normal = normal_llm_answer(question)\n",
    "    rag, evidence = answer_question(question, top_k=top_k)\n",
    "\n",
    "    print(\"=\" * 100)\n",
    "    print(\"QUESTION\")\n",
    "    print(question)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 100)\n",
    "    print(\"NORMAL LLM RESPONSE (NO RETRIEVAL)\")\n",
    "    print(normal)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 100)\n",
    "    print(\"RAG RESPONSE (WITH RETRIEVED CONTEXT)\")\n",
    "    print(rag)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 100)\n",
    "    print(\"RETRIEVED EVIDENCE USED BY RAG\")\n",
    "    for item in evidence:\n",
    "        print(f\"\\n[{item['rank']}] score={item['score']:.4f}\")\n",
    "        print(item[\"text\"])\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 100)\n",
    "    print(\"QUICK OBSERVATION\")\n",
    "    print(\"- Normal response can be generic or unsupported.\")\n",
    "    print(\"- RAG response should be more grounded in the retrieved passages above.\")\n",
    "\n",
    "# Test question for comparison\n",
    "compare_question = \"what is vigyan bherav tantra? explain to a 5 year old\"\n",
    "compare_normal_vs_rag(compare_question, top_k=3)"
]

# We need to clear the outputs for these cells so the user can run them cleanly
for i in [1, 5, 7]:
    if 'outputs' in nb['cells'][i]:
        nb['cells'][i]['outputs'] = []
    if 'execution_count' in nb['cells'][i]:
        nb['cells'][i]['execution_count'] = None

with open("simple_local_rag.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Updated simple_local_rag.ipynb successfully")
